### ISSUE TITLE
圣杯、双飞翼与Flexbox布局

### ISSUE THREAD

**Issue by zmmzmmz** [petterstrong/css-trick#1]
## 简介

[圣杯布局](https://en.wikipedia.org/wiki/Holy_grail_(web_design))是典型的CSS布局问题，圣杯布局是[Matthew Levine](http://alistapart.com/author/matthewlevine)在2006年提出这个名称，双飞翼布局则是源自淘宝UED。但二者都是通过float浮动法。

下面通过复习对比圣杯、双飞翼和现代flexbox布局，用不同方法去解决下图中页面的布局：

![图1](https://cloud.githubusercontent.com/assets/7554325/13628574/2e28562c-e60e-11e5-9bae-905c4c7bf56a.png)

因其长得类似圣杯或者飞翔的小鸟而得名。

而且满足一下需求：

1. left和right的宽度已知，中间自适应
2. 中间内容应放在文档流前面，优先加载，content内容部分依次按照main、left、right加载

所以HTML如下：

```html
<div class="head">head</div>
<div class="content">
    <div class="main">main</div>
    <div class="left">left</div>
    <div class="right">right</div>
</div>
<div class="foot">foot</div>
```

## 基础样式

首先在content使用float前我们需要定义一个清除浮动类。

```css
* {
    margin: 0;
    padding: 0;
}

.cleanfix {
    clear: both;
}
.cleanfix:after {
    content: '.';
    clear: both;
    display: block;
    visibility: hidden;
    height: 0;
    zoom: 1;
}
/* 或者使用 Nicolas Gallagher 创造的 micro clearfix 方法 (http://nicolasgallagher.com/micro-clearfix-hack/) */ 

.head, .foot {
    width: 100%;
    height: 80px;
}
.left, .right, .main {
    float: left;
}
.left {
    width: 40px;
    height: 60px;
    background-color: rgba(10, 190, 20, .43);
}
.right {
    width: 40px;
    height: 80px;
    background-color: rgba(210, 0, 220, .43);
}
.main {
    background-color: #ddd;
}

```

按照上面样式实现下面布局

![屏幕快照 2018-03-06 下午8.34.43](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%888.34.43.png)

我们的目的是要内容部分main自适应，这样的话给main 100%的宽度：

```css
.main {
    width: 100%;
}
```

![屏幕快照 2018-03-06 下午8.38.34](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%888.38.34.png)

content加上width 100%之后导致两侧left，right浮动到下面，但是目的是想要两侧上去，这时可以使用负边距。

main,content,right都是在同一个浮动流中，顺序是main left right。现在main占了100% 从而导致 left 与 right 不能和 main 浮在同一行。

这个时候我们可以利用负边距来让 left 向前移动 （即 margin-left 为正的时候就是和左边的盒子的外边距，那么为负的时候就是像前移动了），为了让left保持对齐到最左侧，需要向左移动-100%，加上下面样式

```css
.left {
    margin-left: -100%;
}
```

会得到下面的布局：

![屏幕快照 2018-03-06 下午8.56.47](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%888.56.47.png)

同理计算right向左移动一个right的宽度，对齐到最右侧

```css
.right {
    margin-left: -40px;
}
```

得到下面布局：

![屏幕快照 2018-03-06 下午8.59.02](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%888.59.02.png)

从元素审查中可以看出left和right是覆盖在main上面。

![屏幕快照 2018-03-06 下午8.59.48](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%888.59.48.png)

那下面问题来了，怎么使得main的被覆盖部分往里收呢？**这就是圣杯布局与双飞翼布局的根本区别。**

基本样式：

```css
* {
    margin: 0;
    padding: 0;
}
.cleanfix {
    clear: both;
}
.cleanfix:after {
    content: '.';
    clear: both;
    display: block;
    visibility: hidden;
    height: 0;
    zoom: 1;
}
.head, .foot {
    width: 100%;
    height: 80px;
}
.head {
    background-color: rgba(200, 200, 200, .35);
}
.foot {
    background-color: rgba(90, 190, 200, .43);
}

.left, .right, .main {
    float: left;
}
.left {
    width: 40px;
    height: 60px;
    background-color: rgba(10, 190, 20, .43);
    margin-left: -100%;
}
.right {
    width: 40px;
    height: 80px;
    background-color: rgba(210, 0, 220, .43);
    margin-left: -40px;
}
.main {
    background-color: #ddd;
    width: 100%;
}
```

## 圣杯布局

圣杯布局的思想是给content添加padding-left和padding-right，数值分别是left和right的宽度，再将left和right用相对布局 position:relative并分别配合left和right属性，移动到两旁不至于覆盖主内容。

首先，给content添加padding

```css
.content{
    padding: 0 40px 0 40px;
}
```

![屏幕快照 2018-03-06 下午9.17.46](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%889.17.46.png)

再给left和right添加相对定位，移动

```css
.left {
    position: relative;
    left: -40px;
}
.right {
    position: relative;
    right: -60px;
}
```

![屏幕快照 2018-03-06 下午9.21.16](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%889.21.16.png)

HTML：

```html
<div class="head">header</div>
<div class="content cleanfix">
    <div class="main">main</div>
    <div class="left">left</div>
    <div class="right">right</div>
</div>
<div class="foot">footer</div>
```

## 双飞翼布局

双飞翼布局是在main 中创建子wrapper用户放置内容，子wrapper用margin-left和margin-right为left、right两栏留出位置。下面为HTML结构

```html
<div class="head">head</div>
<div class="content cleanfix">
    <div class="main">
        <div class="wrapper">main</div>
    </div>
    <div class="left">left</div>
    <div class="right">right</div>
</div>
<div class="foot">foot</div>
```

添加样式。

```css
.wrap {
    background-color: #FFEB3B;
    margin-left: 40px;
    margin-right: 40px;
}
```

这样得到下面布局

![屏幕快照 2018-03-06 下午9.35.31](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%889.35.31.png)

## flexbox布局

不同于“[怪异的float浮动](http://www.zhangxinxu.com/wordpress/2010/01/css-float%E6%B5%AE%E5%8A%A8%E7%9A%84%E6%B7%B1%E5%85%A5%E7%A0%94%E7%A9%B6%E3%80%81%E8%AF%A6%E8%A7%A3%E5%8F%8A%E6%8B%93%E5%B1%95%E4%B8%80/)”，随着现代浏览器的良好支持，和PostCSS配合AutoPrefixer做兼容， flexbox弹性盒模型已经可以优雅的替代传统的布局方案。

关于跟更多flexbox示例展示看这里[solved-by-flexbox](https://hufan-akari.github.io/solved-by-flexbox/)

flexbox布局思路很简单，由于没有float，我们不用清除浮动什么鬼的。

1、将content设置为弹性盒

```css
.content {
    display: flex;
}
.right {
    width: 40px;
    height: 100px;
    background-color: rgba(210, 0, 220, .43);
}
.left {
    width: 40px;
    background-color: rgba(10, 190, 20, .43);
}
.main {
    background-color: #00BCD4;
}
```

2、将main的flex属性设置为1 自适应宽度

```css
.main {
    flex: 1;
} 
```

![屏幕快照 2018-03-06 下午9.50.31](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%889.50.31.png)

2、设置left的顺序为-1，使main居中

```css
.left {
    order: 1;
}
```

![屏幕快照 2018-03-06 下午9.54.38](http://owpqjlpst.bkt.clouddn.com/images/blog/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8B%E5%8D%889.54.38.png)

全部样式:

```css

.content {
    display: flex;
}
.main {
    flex: 1;
    background-color: #00BCD4;
}
.right {
    width: 40px;
    height: 100px;
    background-color: rgba(210, 0, 220, .43);
}
.left {
    width: 40px;
    background-color: rgba(10, 190, 20, .43);
    order: -1;
}
```

怎样，够简单吧！

## 总结

Float流布局：

圣杯布局和双飞翼布局流程大致如下：

- 搭建 head content foot, content 内部的三个元素全部左浮动，然后清除浮动防止影响 foot
- 给 main 100% 的宽度让他占满一行
- 给 left -100% 的margin-left 让他移动到最左边，给 right 和他宽度一样的负 margin 移动到最右边
- 给 left -100% 的margin-left 让他移动到最左边，给 right 和其宽度的负 margin移动至最右侧
  - 圣杯布局会给 content 内边距，左右分别为 left 和 right的宽度，然后再利用相对定位移动 left 和 right
  - 双飞翼布局会在 main 里面再加一层 wrap ，然后把内容都写在 wrap 里面，正对 wrap 设置他的 margin, 左右外边距和 left 与 right 一样

FlexBox布局

直接设置content为弹性盒，调整left顺序-1，设置main的宽度伸缩自适应flex:1。
样例代码地址：[地址](https://github.com/petterstrong/css-trick/blob/master/assets/layout/demo-1.html)

多亏Flexbox，麻麻再也不用担心我的布局了。溜~
